openapi: 3.0.0
info:
  title: JBH Express Bookstore
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.1
servers:
  - url: http://localhost:3000
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /books:
    get:
      summary: Returns all the books.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - in: query
          name: title
          schema:
            type: string
          description: The title of book to search
      responses:
        "200":
          description: A JSON array of books
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /books/sell:
    post:
      summary: sell a book with any quantity
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - name: title
          in: path
          schema:
            type: string
          description: The title of book to sell
          required: true
        - name: quantity
          in: path
          schema:
            type: integer
          description: The quantity to be sold
          required: true
      responses:
        "200":
          description: A JSON array of books
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
