openapi: 3.0.0
info:
  title: JBH Express Bookstore
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.2
paths:
  /books:
    get:
      tags:
        - List/Search
      summary: Returns all the books.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - in: query
          name: title
          schema:
            type: string
          description: The title of book to search
      responses:
        "200":
          description: A JSON array of books
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    lowercase_title:
                      type: string
                    author:
                      type: string
                    year_published:
                      type: string
                    price:
                      type: integer
                    quantity:
                      type: integer
  /books/sell:
    post:
      tags:
        - Sell
      summary: sell a book.
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/Sell"
      responses:
        "200":
          description: A JSON Object for the book being sold
          content:
            application/json:
              schema:
                type: object
  /books/update:
    post:
      tags:
        - Update
      summary: "A request to get an object from storage"
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/Update"
      responses:
        "200":
          description: A JSON Object for the book being updated
          content:
            application/json:
              schema:
                type: object
  /books/add:
    post:
      tags:
        - Add
      summary: Add a book to the stock.
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/Add"
      responses:
        "200":
          description: A JSON Object for the book being added
          content:
            application/json:
              schema:
                type: object
definitions:
  Update:
    type: object
    required:
      - title
      - price
    properties:
      title:
        type: string
        default: "Emma"
      price:
        type: integer
        default: 1
  Sell:
    type: object
    properties:
      title:
        type: string
        default: "Emma"
      quantity:
        type: integer
        default: 1
  Add:
    type: object
    required:
      - title
      - quantity
    properties:
      title:
        type: string
      author:
        type: string
      price:
        type: integer
      quantity:
        type: integer
