openapi: 3.0.0
info:
  title: JBH Express Bookstore
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.1
servers:
  - url: http://localhost:3000
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /books:
    get:
      summary: Returns all the books.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - in: query
          name: title
          schema:
            type: string
          description: The title of book to search
      responses:
        "200":
          description: A JSON array of books
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    lowercase_title:
                      type: string
                    author:
                      type: string
                    year_published:
                      type: string
                    price:
                      type: integer
                    quantity:
                      type: integer
  /books/add:
    post:
      summary: add a book.
      consumes:
        - application/json
      parameters:
        - in: body
          name: add
          description: The book to add.
          schema:
            type: object
            required:
              - title
              - quantity
            properties:
              title:
                type: string
              author:
                type: string
              price:
                type: integer
              quantity:
                type: integer
      responses:
        "200":
          description: A JSON Object for the book being added
          content:
            application/json:
              schema:
                type: object
  /books/sell:
    post:
      summary: sell a book.
      consumes:
        - application/json
      parameters:
        - in: body
          name: add
          description: The book to sell.
          schema:
            type: object
            required:
              - title
              - quantity
            properties:
              title:
                type: string
              quantity:
                type: integer
      responses:
        "200":
          description: A JSON Object for the book being sold
          content:
            application/json:
              schema:
                type: object
  /books/update:
    post:
      summary: update a book's price.
      consumes:
        - application/json
      parameters:
        - in: body
          name: add
          description: update a book's price.
          schema:
            type: object
            required:
              - title
              - price
            properties:
              title:
                type: string
              price:
                type: integer
      responses:
        "200":
          description: A JSON Object for the book being added
          content:
            application/json:
              schema:
                type: object
